[build]
  command = "source venv/bin/activate && npm run build && uvicorn main:app --host 0.0.0.0 --port $PORT"
  publish = "dist"

[dev]
  command = "source venv/bin/activate && npm start"
  publish = "dist"
