[build]
  command = "source venv/bin/activate && npm run build "
  publish = "dist"

[dev]
  command = "source venv/bin/activate && npm run serve"
  publish = "dist"
[functions]
  directory = "netlify/functions"

